name: ci-cd-flow

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Development Code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
          
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build --if-present
      
      - name: Check linting and formatting
        # Custom script for checking the linting and formatting being in place
        run: npm run lint

      - name: Persist workflow data as artifact
        uses: actions/upload-artifact@v3
        with:
          name: care-frontend-merge-artifact
          path: ./build

  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repository
    needs: [ build ]
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
#           file: ./Dockerfile
          file: ./src/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/clockbox:latest
